# Generated by Django 3.1 on 2020-08-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_id',
        ),
    ]
