# Generated by Django 3.1 on 2020-08-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200816_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter_id', models.IntegerField(verbose_name='章节id')),
                ('chapter_name', models.CharField(max_length=100, verbose_name='章节名')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='书籍id')),
            ],
            options={
                'db_table': 'tb_chapter',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='正文')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.chapter', verbose_name='章节')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
