# Generated by Django 3.1 on 2020-08-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_chapter_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='tb_content',
        ),
    ]
