# Generated by Django 3.1 on 2020-08-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200817_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(default=None, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(default=None, verbose_name='正文'),
        ),
    ]
