# Generated by Django 3.1 on 2020-08-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200819_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_id',
        ),
    ]
