# Generated by Django 3.1 on 2020-08-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_chapter_chapter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='book_id',
            new_name='book',
        ),
    ]
