# Generated by Django 3.1 on 2020-08-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200820_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.CharField(max_length=100, verbose_name='书籍id'),
        ),
    ]
