# Generated by Django 3.1 on 2020-08-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200820_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='book',
            new_name='book_id',
        ),
    ]
