# Generated by Django 3.1 on 2020-08-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200820_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_id',
            field=models.IntegerField(default=None, verbose_name='章节id'),
        ),
    ]
