# Generated by Django 3.1 on 2020-08-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_chapter_chapter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_id',
        ),
    ]
