# Generated by Django 3.1 on 2020-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_chapter_chapter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_id',
            field=models.IntegerField(default=None, verbose_name='章节id'),
        ),
    ]
