# Generated by Django 3.1 on 2020-08-16 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelves',
            old_name='updated_time',
            new_name='update_time',
        ),
    ]
