# Generated by Django 3.1 on 2020-08-25 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200820_2131'),
        ('bookshelves', '0002_auto_20200816_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelves',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.chapter', verbose_name='章节'),
        ),
    ]
