# Generated by Django 3.1 on 2020-08-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_chapter_chapter_id'),
        ('bookshelves', '0003_bookshelves_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelves',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.chapter', verbose_name='章节'),
        ),
    ]
